# Generated by Django 5.1.1 on 2024-12-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='name',
            new_name='City',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='Phone_Number',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='Project_Description',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='Project_Requirements',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='Type_of_Project',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='message',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='Pincode',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
