# Generated by Django 5.1.1 on 2024-12-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_name_contactmodel_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='Pincode',
            field=models.IntegerField(blank=True),
        ),
    ]
