# Generated by Django 5.1.1 on 2024-12-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_contactmodel_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='Pincode',
            new_name='Id',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='City',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='State',
        ),
    ]
