# Generated by Django 5.1.1 on 2024-12-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_pincode_contactmodel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
